[theme]
base = "light"

[client]
toolbarMode = "auto"

[server]
runOnSave = true

[theme]
base="light"
primaryColor="#2563eb"         # buttons, links
backgroundColor="#ffffff"
secondaryBackgroundColor="#f6f7fb"
textColor="#0f172a"
font="sans serif"

[theme]
base="light"
primaryColor="#2563eb"
backgroundColor="#f8fafc"
secondaryBackgroundColor="#f1f5f9"
textColor="#0f172a"
font="sans serif"

[server]
headless = true

[ui]
hideTopBar = false

[theme]
base="dark"
primaryColor="#60a5fa"
backgroundColor="#0f172a"
secondaryBackgroundColor="#1e293b"
textColor="#f8fafc"
font="sans serif"

[theme]
base = "light"
primaryColor = "#2563eb"            # Indigo-600 (actions, links)
backgroundColor = "#0b1220"         # Deep navy background
secondaryBackgroundColor = "#11172a" # Card background
textColor = "#e6eefc"               # Near-white text
font = "sans serif"